version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  backend:
    build: ./src
    ports:
      - '8000:8000'
    env_file: .env
    depends_on:
      - redis

  dashboard:
    build: ./src/dashboard
    ports:
      - '3000:3000'
    depends_on:
      - backend

  # Optional: SUMO container (or run SUMO locally)
  sumo:
    image: eclipse/sumo:latest
    command: tail -f /dev/null
    ports: []
